version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-device-info
    versions:
    - 8.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
  - dependency-name: react-native-form-progress
    versions:
    - 1.0.21
